#!/usr/bin/env bash
# a program to display to 1 - 20 and displays the supertitious thigs

var=1

while [ $var -le 20 ]
do
	case $var in
	5) echo "bad luck form China";;
	10) echo "bad luck from Japan";;
	18) echo "bad luck from Italy";;
	esac
	echo $var

	var=$((var + 1))
done

